---
title: "Week 2: dplyr and The Census"
description: "Manipulating data from the ACS census"
date: 2026-09-04
---

## Troubleshooting
1. On RStudio --> files --> click the .Rproj link to open it --> to be able to see the Build tab

## Essential packages
1. **dplyr** - data wrangling
2. **tidycensus** - to access US Census data

## Other notes
### Vocabulary
* Tibble - a prettier version of a dataframe. Only works on tidyverse/tibble package

### Most important functions
1. _filter()_ - for rows
2. _select()_ - for columns
3. _mutate_ - call a function on existing columns and adds a column with results
4. _arrange()_ - change order of rows (asc(), desc() by a specific column)
5. _group_by()_ - sum up rows based on a variable
6. _summarize()_ - group_by() but with any summary statistic like _mean_
7. shortcut for pipe - Ctrl + Shift + m

## The Census
* First started a decennial census - every 10 years, each person is asked 10 questions
* Then formalised into an American Community Survey (ACS) --> samples 3% of households to generate a population estimate
  * 1-year ACS: Places > 65,000 (not very useful)
  * 5-year ACS: Per tract; average over 5 years of samples (e.g. 2011-2015 to generate 2016 census) --> Dead now :()
  * Each Base Table has a table number (19013) + line number (001)  + margin of error - MoE (E) e.g. B19013_001E
  * **Scales** - State --> County --> Tract (Neighborhood, 5000-8000 people; boundaries always change) --> Block groups (but high MoE) --> Block (Decennial only)
    * Longitudinal tracts have been made (NHGIS/LTDB)
  
### Calling data from tidycensus
1. _library(tidycensus)_
2. load_variables()
3. **GEOID** - a unique identifier
  * First 2 digits: state
  * Next 3 digits: county
  * Next 6 digits: tract
  * +1 extra number
4. To look at codes: _vars <- load_variables(2023, "acs5")_



``` {r}
#install.packages("tidycensus")
library(tidycensus)

# for example
data <- get_acs(geography = "county", 
                variables = c("B19013_001","B01003_001"),
                state = "PA",
                year = 2023,
                survey = "acs5",
                #output = "wide"
                )

#this will generate a table in long format, where each different variable is in a separate row under the same column name "Variable"
# need to convert to wide format so that each variable is under a different column --> SO, SPECIFY: output = "wide"

``` 

