---
title: "Week 3: More about margins of error"
description: "____"
date: 2026-09-11
---

## Why plot data?

* **Ansombe's Quartet** - revealing the need to visualise data to check scatterplot/trends
* A plot is a mapping from columns in your data to visual properties on your page

## How data is plotted

| My data | Page |
|---|---|
| Estimate | Position on y-axis |
| Population | Position on x-axis |
| Reliability | Colour |
| MoE | Size |

# ggplot
ggplot(dataframe,
       mapping = aes(x=x,
            y=y)         _#Aesthetic mappings (assigning columns to DATA plotted)_
       )+     #Creates a blank canvas
  geom_<shape>( )+ _#Add aes() for columns if needed, to assign CHARACTERISTICS to the plot)_
  _#Decorations_



### Arguments inside aes()
* **color** - assign a colour, or a column_name
* **ggplot(aes(x = reorder(NAME, estimate), y = estimate))** - reorder the NAME column by the length of estimate --> so it is in order according to size of the y (e.g. height of bar chart etc)


### Potential shapes for geom_
* **point** (scatterplot)
* **smooth** (to add best fit line)
* **histogram** (specify bins/bindwidth for best results)
* **boxplot**
* **col**
* **line**
* **errorbar(aes(ymin = estimate - moe, ymax = estimate + moe)** - need set upper and lower limit for all y-values. Hence need to have the y-value AND moe for each row

### Decorations
* **facet_wrap(~column_name)** - to facet the plots according to a category
* **coord_flip()** - to flip x and y axis, often to increase reliability
* **theme_minimal()**
* **scale_y_continuous(labels = scalls::comma)** - add commas to numbers with e.g. 1000 --> 1,000

***

# Coefficient of variation (CV)
Is the relative measure of sampling error
* CV = (standard_error/estimate) * 100
* SE, standard error is a standard number like 0.95 - which reflects the confidence level
* MoE is based on the characteristics of the sample - e.g. size / variance of sample

Generally,

| CV | Reliability |
| -------- | -------- |
| Low (15%) | High reliability |
| Medium (15-30%) | Medium |
| High (30%) | High sampling error |

# Derived uncertainty: How?
* MoE for both numerator and denominator need to be derived into a new MoE
* use function!
  * **moe_sum(moe, estimate)** - for adding estimates together
  * **moe_prop()** - for a proportion, get one estimate as share of another
  * **moe_ratio()** - for a ratio (of non equivalent value, unlike proportion which often operates on the same population)
  
### How to use moe_prop()
  mutate(
    share     = below_povertyE / totalE,
    share_moe = moe_prop(below_povertyE, totalE, ## ORDER: estimate, estimate(denominator), moe, moe(denominator)
                         below_povertyM, totalM)
  )


## So how to measure uncertainty for change over time?
* For ACS 5 it is difficult because there are a lot of overlapping intervals (e.g. 2019-**2023**, and 2018-**2022** actually has many overlapping years)
  * Hence need to compare non-overlapping intervals like 2014-**2018** and 2019-**2023**


## Making functions for acs
```{r}
get_poverty <- function(yr) {
  get_acs(
    geography = "county",
    variables = "B07012_002",
    state     = "NY",
    year      = yr,
    survey    = "acs5"
  ) %>%
    mutate(period = paste0(yr - 4, "-", yr)) # GIVES A COLUMN WITH STRING. E.G. "2014-2018", for get_poverty(2018)
}
```


### windows + . for emojis!!!!



Homework
1. start on rscript,
2. then make a nice Quarto submission

Notes for homework
- #| code-fold: false
  - # this chunk stays visible
- #| include: false
  - # to hide a chunk entirely
- #| echo: false	Hide the code, show the output
- #| message: false	Suppress package startup messages
- #| warning: false	Suppress warnings
- #| fig-cap: "..."	Add a figure caption
Use message: false and warning: false on your data pull chunks. tidycensus is chatty, and its progress output does not belong in a finished report.
