---
title: "About Me!"
format: html
---

## Background

I just graduated from University College London in BSc Urban Studies, where I was first introduced to the world of spatial analysis. A year ago, I built my first map in QGIS, layering London’s air pollution over its social housing. What began as an experiment in technical flair turned into a moment of reckoning. The darkest reds traced the city’s most deprived neighborhoods, exposing inequality in color. That map taught me that data can clarify or conceal truth, reinforcing my beief that evidence-based approaches are foundational in making equitable and transparent policy decisions.

At Penn, I'm hoping to deepen my skills in geospatial analysis, machine learning, and data integration, while learning how to translate these insights into actionable strategies for policymakers and communities alike.


## Skills

- **Languages & Tools:** R, Python, Quarto, Git
- **Spatial:** QGIS, ENVI, Google Earth Engine
- **Data:** UK ONS Census, Singapore Census & LTA Datamall, US Census / ACS (soon)

## Portfolio
View my **Portfolio 2026** [here](data/img/portfolio.pdf)!
<iframe src="data/img/portfolio.pdf" width="100%" height="600px"></iframe>

## Get in Touch

- Email: chlauryn@upenn.edu
- GitHub: [@chlauryn](https://github.com/chlauryn)

