{
  "hash": "051dad92851bd0885b58a8f60e9e2a96",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Lauryn Chan\"\ndate: 2026-09-04\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\nlibrary(dplyr)\n```\n:::\n\n\n---\n\n## The question\n\nIn this analysis, I look at median home value across counties in New Jersey, and\nask which communities we measure most and least reliably. I just moved to the US, and was picked up by my uncle who lives in NJ - would love to know more about the beautiful houses there and how property prices compare!\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Can be changed and the rest of the code will follow!\n\nmy_state <- \"NJ\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25077_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21  4\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  GEOID NAME                          B25077_001E B25077_001M\n  <chr> <chr>                               <dbl>       <dbl>\n1 34001 Atlantic County, New Jersey        272700        4435\n2 34003 Bergen County, New Jersey          593200        4951\n3 34005 Burlington County, New Jersey      326700        3737\n4 34007 Camden County, New Jersey          262200        3072\n5 34009 Cape May County, New Jersey        395000        8798\n6 34011 Cumberland County, New Jersey      205600        4394\n```\n\n\n:::\n:::\n\n\n\n***The numbers of rows (21) matches the number of counties in New Jersey.***\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add column with MoE\ncounty_data <- county_data |> \n  mutate(moe_pct = B25077_001M / B25077_001E * 100)\n\n# Arrange rows according to descending MoE\ncounty_data |> \n  arrange(desc(moe_pct)) |> \n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   GEOID NAME                          B25077_001E B25077_001M moe_pct\n   <chr> <chr>                               <dbl>       <dbl>   <dbl>\n 1 34033 Salem County, New Jersey           223000        6636    2.98\n 2 34017 Hudson County, New Jersey          508600       12318    2.42\n 3 34009 Cape May County, New Jersey        395000        8798    2.23\n 4 34011 Cumberland County, New Jersey      205600        4394    2.14\n 5 34021 Mercer County, New Jersey          351000        6540    1.86\n 6 34019 Hunterdon County, New Jersey       498800        9233    1.85\n 7 34041 Warren County, New Jersey          323100        5865    1.82\n 8 34001 Atlantic County, New Jersey        272700        4435    1.63\n 9 34035 Somerset County, New Jersey        523900        8197    1.56\n10 34037 Sussex County, New Jersey          342800        4709    1.37\n```\n\n\n:::\n:::\n\n\n***Salem County has the largest margin of error relative to its estimate, of 2.98%.***\n\n---\n\n## Optimising categories of margin of error\n\nTo comput categories for margins of error, Jenks breaks are used to minimise variance within each of the 3 categories of confidence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(classInt)\n\njenks <- classInt::classIntervals(\n  county_data$moe_pct,\n  n = 3,\n  style = \"jenks\"\n)\n\njenks$brks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8147052 1.3736873 1.8632479 2.9757848\n```\n\n\n:::\n:::\n\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct <= jenks$brks[2] ~ \"High confidence\",\n    moe_pct <= jenks$brks[3] ~ \"Moderate confidence\",\n    TRUE                    ~ \"Low confidence\"\n  ))\n\n# To remove, during experimentation\n# county_data$reliability <- NULL\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability             n\n  <chr>               <int>\n1 High confidence        12\n2 Low confidence          4\n3 Moderate confidence     5\n```\n\n\n:::\n:::\n\n\n\n***12 counties have high confidence of less than 1.37% margin of error. There are 5 counties with moderate confidence, and 4 with low confidence.***\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a wide pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                          myvarE myvarM   popE  popM\n  <chr> <chr>                          <dbl>  <dbl>  <dbl> <dbl>\n1 34001 Atlantic County, New Jersey   272700   4435 274704    NA\n2 34003 Bergen County, New Jersey     593200   4951 954717    NA\n3 34005 Burlington County, New Jersey 326700   3737 464226    NA\n4 34007 Camden County, New Jersey     262200   3072 524042    NA\n5 34009 Cape May County, New Jersey   395000   8798  95236    NA\n6 34011 Cumberland County, New Jersey 205600   4394 152915    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct <= jenks$brks[2]  ~ \"High confidence\",\n    moe_pct <= jenks$brks[3] ~ \"Moderate confidence\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow we compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  ) |> \n  arrange(avg_population)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability         n_counties avg_population\n  <chr>                    <int>          <dbl>\n1 Moderate confidence          5        248776.\n2 Low confidence               4        255900.\n3 High confidence             12        583294.\n```\n\n\n:::\n:::\n\n\nThere doesn't seem to be a trend between confidence and population size. Maybe the categories of confidence are too arbitrary.\n\nIt would be better to plot, using the actual numerical values of margins of error!\n\n#### Scatterplot of margins of error against population size\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate scatterplot\nggplot(\n  data = county_wide,\n  mapping = aes(x = popE, y = moe_pct)\n) +\n  geom_point() +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](assignment2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWe see a downwards trends based on the best-fit line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Computing Pearson's correlation coefficient\ncor(county_wide$popE, county_wide$moe_pct, use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.6136624\n```\n\n\n:::\n:::\n\n\n**The Pearson's correlation coefficient indicates that there is a moderately strong negative correlation between population and margin of error (-0.6136624), indicating that as population size increases, the margin of error for house values decreases. This corresponds to how a larger sample size increases reliability as it reduces random error.**\n\n---\n\n## What this means for policy\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Final table\nfinal_data <- county_data |> \n  inner_join(county_wide, by=c(\"moe_pct\",\"NAME\",\"GEOID\",\"reliability\")) |> \n  select(-myvarM,-popM) |> \n  arrange(moe_pct)\n```\n:::\n\n\n\n::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  head(final_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  GEOID NAME           B25077_001E B25077_001M moe_pct reliability myvarE   popE\n  <chr> <chr>                <dbl>       <dbl>   <dbl> <chr>        <dbl>  <dbl>\n1 34023 Middlesex Cou…      439300        3579   0.815 High confi… 439300 861535\n2 34003 Bergen County…      593200        4951   0.835 High confi… 593200 954717\n3 34031 Passaic Count…      439400        4112   0.936 High confi… 439400 518289\n4 34039 Union County,…      488800        4723   0.966 High confi… 488800 572549\n5 34015 Gloucester Co…      283500        2851   1.01  High confi… 283500 304504\n6 34025 Monmouth Coun…      566500        5868   1.04  High confi… 566500 643615\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  tail(final_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  GEOID NAME           B25077_001E B25077_001M moe_pct reliability myvarE   popE\n  <chr> <chr>                <dbl>       <dbl>   <dbl> <chr>        <dbl>  <dbl>\n1 34019 Hunterdon Cou…      498800        9233    1.85 Moderate c… 498800 129448\n2 34021 Mercer County…      351000        6540    1.86 Moderate c… 351000 383286\n3 34011 Cumberland Co…      205600        4394    2.14 Low confid… 205600 152915\n4 34009 Cape May Coun…      395000        8798    2.23 Low confid… 395000  95236\n5 34017 Hudson County…      508600       12318    2.42 Low confid… 508600 710478\n6 34033 Salem County,…      223000        6636    2.98 Low confid… 223000  64973\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\nThe county we can most safely predict house values of is Middlesex County, with a median house value of $440,000. They have the lowest margin of error of 0.81%, thanks to its relatively high population of 860,000.\n\nWe have the lowest confidence regarding median home values in Salem County, with the lowest population of 65,000 which likely contributes to its high margin of error of 2.98%. \n\nThat's because the 5-year ACS only samples approximately 5% of households over 5 years in total, rather than a complete count of all housing units. A smaller county would yield a smaller sample size, increasing random error for house value estimates. The use of the median value, however, helps to counter the effect of random error by ignoring extremes.\n\n**What could go wrong?** \n\nThe margin of error introduces false positives about a place for policy analysis. If a county has a high estimated median house value, but also high margin of error, the state might incorrectly conclude that housing is more expensive in that area and allocate less housing assistance (and vice versa). This means resources are not allocated optimally to those in need. This is particularly disadvantageous for those who live in smaller counties with high margins of error whose needs are not represented in the census well.\n",
    "supporting": [
      "assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}